server:
  port: 3010

logger:
  filename: 'someone'
  dirname: '/Users/youngsik/feature/someone_project/backend/someone/logs/console'

database:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'jms12jms!@'
  database: 'sideproject'
  synchronize: false
  logging: true
  logger:
    filename: 'someone'
    dirname: '/Users/youngsik/feature/someone_project/backend/someone/logs/query'

resource:
  savePath: '/Users/youngsik/feature/someone_project/backend/someone/public'
  baseUrl: '/public'


jwt:
  accessSecret: 'access_key'
  accessExpriesIn: 180
  refreshSecret: 'refresh_key'
  refreshExpriesIn: 3600

cryptoJS:
  encryptSecret: 'refresh_encrypt_key'
