server:
  port: 3010

database:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'jms12jms!@'
  database: 'sideproject'
  synchronize: false
  logging: true

jwt:
  accessSecret: 'access_key'
  accessExpriesIn: 180
  refreshSecret: 'refresh_key'
  refreshExpriesIn: 3600

cryptoJS:
  encryptSecret: 'refresh_encrypt_key'
