server:
  port: 9910

logger:
  filename: 'balloonmagic'
  dirname: '/logs/prod/console'

database:
  type: 'mysql'
  host: '132.226.23.243'
  port: 3306
  username: 'admin'
  password: 'jms12jms12'
  database: 'balloonmagic'
  synchronize: false
  logging: true
  logger:
    filename: 'balloonmagic'
    dirname: '/logs/prod/query'
    
resource:
  savePath: '/public'
  baseUrl: '/public'

jwt:
  accessSecret: 'access_key'
  accessExpriesIn: 180
  refreshSecret: 'refresh_key'
  refreshExpriesIn: 3600

cryptoJS:
  encryptSecret: 'refresh_encrypt_key'
